### ISSUE TITLE
Stereo to mono?

### ISSUE THREAD

**Issue by brad-colbert** [tierneytim/btAudio#11]
Still, and again, awesome work! Thanks!

Is there a way to merge left and right data to produce the same audio on both output channels?

**Comment by tierneytim** [comment]
yes, should be very easy. If you look [here](https://github.com/tierneytim/btAudio/blob/dcd4bf5eb592377afc28112ffa10681e0a151716/src/btAudio.cpp#L204) you could do the following 
```
fy[0]= (fy[0]+fy[1])/2;
fy[1]= (fy[0]+fy[1])/2;
```
