### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by dave3389** [tierneytim/btAudio#27]
Building in release mode
Compiling .pio\build\esp32doit-devkit-v1\src\main.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libd32\btAudio\webDSP.cpp.o
In file included from .pio/libdeps/esp32doit-devkit-v1/btAudio/src/webDSP.cpp:1:
.pio/libdeps/esp32doit-devkit-v1/btAudio/src/webDSP.h:5:9: fatal error: WebServer.h: No such file or directory

but i am sure the "WebServer.h" exists.

**Comment by dave3389** [comment]
![image](https://user-images.githubusercontent.com/102789500/196862075-d20287e6-f034-4bac-9d3b-36adf95de5cf.png)
i saw this one,and now i fix it.it works,thanks man.

**Comment by tierneytim** [comment]
good job, glad it works
